---
all:
  vars:
    ansible_user: sre
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    # K3s version to install - will update l8r
    k3s_version: v1.28.5+k3s1
    # Network CIDR for pods
    k3s_cluster_cidr: 10.42.0.0/16
    # Network CIDR for services
    k3s_service_cidr: 10.43.0.0/16
    # Disable built-in traefik (optional - you can enable if needed)
    k3s_disable_traefik: true
    # Timezone
    system_timezone: America/Chicago

k3s_cluster:
  children:
    control_plane:
      hosts:
        k3s-control-1:
          ansible_host: 192.168.1.210
    
    workers:
      hosts:
        k3s-worker-1:
          ansible_host: 192.168.1.211
        k3s-worker-2:
          ansible_host: 192.168.1.212
        k3s-worker-3:
          ansible_host: 192.168.1.213
