---
all:
  hosts:
    pve_1:
      ansible_host: 192.168.1.90
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_proxmox

  vars:
    proxmox_api_host: 192.168.1.90
    proxmox_api_user: "ansible@pam"
    proxmox_api_token_id: "ansible"
